server:
  port: 8088
spring:
  application:
    name: updownload
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/alone?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: wby321
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: MYSQL
      show-sql: true
      properties:
        hibernate.id.new_generator_mappings: true
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
        hibernate.cache.use_minimal_puts: true
    driver-class-name: com.mysql.jdbc.Driver

dev:
  filePath: uploadFile